### ISSUE TITLE
Missing sourcePoint and targetPoint

### ISSUE THREAD

**Issue by mgax** [kieler/klayjs#1]
In some cases, the return value of the layout algorithm is missing `sourcePoint` and `targetPoint` for an edge. Here is an example input and output: https://gist.github.com/mgax/13c0d1ff02a6c9bcc5ed.

**Comment by uruuru** [comment]
Your specified edge crosses a hierarchy boundary (as B is a child of A and C is on the same level as A). Our algorithm does (by default) not support cross hierarchy edges, they are ignored completely.

We however offer a layout option `layoutHierarchy` that supports those edges. You add it to the properties of the root level node like this:

``` javascript
{
  "properties": {"layoutHierarchy": true},
  "children": {
  [...]
}
```

Let me know if this helps.

**Comment by mgax** [comment]
I've added `"options": {"layoutHierarchy": true}` to the `$klay.layout` call, that did the trick, thanks!

**Comment by uruuru** [comment]
For future reference, we changed `layoutHierarchy` to be `true` by default.
