### ISSUE TITLE
Max graph width and node 'wrap'

### ISSUE THREAD

**Issue by robclouth** [kieler/klayjs#14]
Is there a way to specify a maximum graph width, beyond which the nodes are wrapped so that they stay inside the bounds? Kind of like word wrap in text editors.

**Comment by uruuru** [comment]
When you say width, do you refer to a left-to-right layout?

**Comment by robclouth** [comment]
I mean a top to bottom layout. If nodes are on the same level, they are
positioned horizontally; I'm asking if there is an option to limit the
maximum horizontal width, and push any nodes that are outside that width
onto the next level.

**Comment by robclouth** [comment]
So that they 'wrap' like the words do in text editors when the line is too
long.

**Comment by uruuru** [comment]
Sadly not. There are some solutions to this in the literature and we are working on features ourselves, but I cannot say if there will be something added in the near future.

Depending on the structure of your graph you may be able to work around the issue by introducing dummy edges for the layout only to force nodes to different layers.

**Comment by robclouth** [comment]
Thanks. What generally makes the nodes go onto another level? The number of
edges?

**Comment by uruuru** [comment]
Pairs of nodes connected by an edge must not be on the same level (also _layer_). There are different strategies that are explained in more detail in our [wiki](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/The+Five+Phases). See the section on _Phase 2: Layering_.

**Comment by robclouth** [comment]
Hmmm ok. So potentially I could perform layout then if any node x position
is over the maximum width, connect it to another one on the same y with an
invisible dummy connection.

**Comment by uruuru** [comment]
For instance.

**Comment by forresto** [comment]
Max width would be useful for `direction: 'RIGHT'` as well... I'd like to have this graph "wrap" with window width:

![](https://cloud.githubusercontent.com/assets/395307/19731744/75926976-9b6c-11e6-9ebb-cdeb8e7021e3.png)

As I resize the browser window, I'd like to pass in a `maxWidth` and relayout, and klay would decide the height.

**Comment by uruuru** [comment]
Agree. For path-like graphs we already support such a wrapping and are working on something that would help your graph as well. I assume by wrapping with the window you mean that the flow should first return from the very right to the left-most position of the window?

**Comment by idea-launch-lab** [comment]
We have similar need for left-to-right graphs that are too long. Current behavior is to scale the graph so that complete graph is visible, but an option that 'wraps' graph would be great to have. However, one possible issue is how to handle nested groups. Below is a typical graph we are visualizing... 

![screen shot 2016-10-28 at 9 34 10 am copy](https://cloud.githubusercontent.com/assets/5922613/19808419/c6aa77cc-9cf2-11e6-89fd-473a703989c7.png)

Thanks.

**Comment by uruuru** [comment]
@sid-thakur thanks for the example. The nested nodes are indeed an interesting problem. I'll think about it.

**Comment by uruuru** [comment]
In elkjs there are two options which address these use cases:

* for top-down layout with restricted width the [COFFMAN_GRAHAM](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-strategy.html) layering strategy can be used alongside the [layerBound](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-layering-coffmanGraham-layerBound.html) option. Note however that only the number of real nodes can be restricted (i.e. edges are not considered).
* for the left-right layout with restricted width the [Graph Wrapping](http://www.eclipse.org/elk/reference/options/org-eclipse-elk-layered-wrapping-strategy.html) can be used. 

I haven't thought about @sid-thakur's example yet but it seems to be rather challenging to me.
