### ISSUE TITLE
Edge routing with fixed nodes

### ISSUE THREAD

**Issue by mgax** [kieler/klayjs#2]
Is it possible to keep the node positions from an input graph, and only perform edge routing?

**Comment by uruuru** [comment]
Strictly speaking, no. The underlying algorithm is just not designed to support this.

There is, however, the option to keep the nodes _vaguely_ in their positions. If you want to give it a try, specify `x` and `y` coordinates for the nodes and set the following options.

``` javascript
cycleBreaking: "INTERACTIVE",
crossMin: "INTERACTIVE",
nodeLayering: "INTERACTIVE",
nodePlace: "INTERACTIVE"
[...]
{ 
  id: "n1",
  x: 40,
  y: 40,
  width: 20,
  height: 20
}
[...]
```

You can find more information on the options here: [KLay Layered Options](https://rtsys.informatik.uni-kiel.de/confluence/display/KIELER/KLay+Layered+Layout+Options)

If this is not sufficient for you, something like [Libavoid](https://github.com/mjwybrow/adaptagrams) might be of interest to you. There's a javascript port [avoid.js](https://github.com/worklez/avoid.js/).

**Comment by mgax** [comment]
At first glance, that results in some weird routing decisions, but I'll look into avoid.js, thanks for pointing it out.

**Comment by uruuru** [comment]
Would you be able to share (maybe privately) your results? I could tell you if it's an issue with the configuration or whether it's expected behavior.

**Comment by mgax** [comment]
Sure, I'll create a minimal example tomorrow.

**Comment by mgax** [comment]
https://gist.github.com/mgax/b6e1e4dd1bd23a1df436

**Comment by uruuru** [comment]
Thanks. Actually, this is kind of expected behavior for this configuration (not that we say it's a good layout result!) :).
You can improve it a bit by using `nodePlace: 'BRANDES_KOEPF'`, however, this will alter node positions a little more. 

Anyway, thanks for the example. We believe we might be able to improve on this sometime in the future (rather long-term though).

**Comment by mgax** [comment]
Ok, thanks for taking the time to look into this :)
