### ISSUE TITLE
Allow node and edge id's as integers.

### ISSUE THREAD

**Issue by TimZaman** [kieler/klayjs#20]
Otherwise throws an error "Invalid format for 'id'. Must be a string,(...)". I guess integers are fine right.

Almost forgot to say, this repo was just what i was looking for, a minimal but highly effective  elegant implementation, thanks.

**Comment by uruuru** [comment]
Good point, should definitely be allowed. Sadly it requires a change in the Java code, which I probably won't touch anymore until klayjs is migrated to [ELK](https://github.com/OpenKieler/klayjs#elk---eclipse-layout-kernel) (the successor on the java side).

**Comment by uruuru** [comment]
Fixed in elkjs.
