### ISSUE TITLE
Global layout option not applied

### ISSUE THREAD

**Issue by uruuru** [kieler/klayjs#22]
I feel specifying node label placement as a global option is not applied to the individual nodes. Check why. 

`'de.cau.cs.kieler.nodeLabelPlacement': 'OUTSIDE V_TOP H_CENTER',`

**Comment by le-cds** [comment]
Depending on what you mean by "global option", this might be expected behavior. Setting this on the parent node will not result in the setting being applied to the child nodes as well.

**Comment by uruuru** [comment]
The global options can be passed separately to the layouter instance. Each option should explicitly be applied to all graph elements (unless the option is already set).

**Comment by le-cds** [comment]
Right, I thought that's what you were getting at. Just wanted to make sure. ;)

**Comment by uruuru** [comment]
Fixed in elkjs.
