### ISSUE TITLE
pretty development version

### ISSUE THREAD

**Issue by rhalff** [kieler/klayjs#24]
I wonder if it would be possible to provide a more readable version of klayjs for development purposes.

I understand gwt has a `-style PRETTY` option while compiling, maybe it can be used to also generate a `klay.dev.js` file.

See: http://www.gwtproject.org/doc/latest/FAQ_DebuggingAndCompiling.html

At the moment I'm trying to load the worker with webpack which fails and the obfuscated version is impossible to debug.

**Comment by uruuru** [comment]
I struggle with debugging the obfuscated code myself over and over again. I
already tried the `pretty` option a while ago but it didn't work for a
reason I don't remember.

My hope is that the latest gwt version will resolve this issue (which isn't
used yet).

**Comment by rhalff** [comment]
Thanks for the quick reply.

I checkout out the source code of klayjs as described in #16

I added the pretty style overhere within the build file:
https://git.rtsys.informatik.uni-kiel.de/projects/KIELER/repos/pragmatics/browse/build/de.cau.cs.kieler.klayjs/build.xml?at=klayjs#37

Then executed both `gradle webworkerlinker` and `gradle plainjslinker` and it does seem to work.

It would require however an additional build step otherwise the default is unobfuscated.

Update:

The worker script also loads correctly, but I had to remove `$wnd.` (window) prefix and a peculiar `$wnd.Array = function(){};` in the generated klayjs_worker.js file.

**Comment by uruuru** [comment]
Which gwt version did you use?

**Comment by rhalff** [comment]
It's using gwt-2.8.0-rc2 (located in build/gwt), except from the flag I didn't change anything within the repository files.

**Comment by uruuru** [comment]
Ok, thanks for verifying this. I'll incorporate it as soon as I touch the built system again.

**Comment by uruuru** [comment]
A pretty version is now available in elkjs.
