### ISSUE TITLE
How to compile from original source?

### ISSUE THREAD

**Issue by Rush** [kieler/klayjs#30]
Very interesting project, it does not seem to be very open source however. Is it on purpose?

If not on purpose and if this project is supposed to be open source then where is the original source exactly? Do you have any makefiles/toolchain files to build KlayJS from the original Java source?

**Comment by Rush** [comment]
I did find this issue now https://github.com/OpenKieler/klayjs/issues/16

**Comment by uruuru** [comment]
Also see #29.
